from __future__ import annotations

from pathlib import Path

import pandas as pd


def save_dataframe(
    dataframe: pd.DataFrame,
    filename: str,
    output_dir: Path,
) -> Path:
    """
    Save a DataFrame as a CSV file.
    """
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    path = output_dir / filename

    dataframe.to_csv(
        path,
        index=False,
    )

    return path


def build_research_snapshot(
    result,
) -> pd.DataFrame:
    """
    Build a compact one-row snapshot of the
    integrated equity research result.
    """
    summary = result.investment_summary

    return pd.DataFrame(
        [
            {
                "target_ticker": (
                    result.target_ticker
                ),
                "peer_count": len(
                    result.peer_financials
                ),
                "valuation_method_count": len(
                    result.valuation_summary
                ),
                "estimated_wacc": (
                    result.estimated_wacc
                ),
                "market_price": (
                    summary.get(
                        "market_price"
                    )
                ),
                "consensus_value": (
                    summary.get(
                        "consensus_value"
                    )
                ),
                "valuation_upside": (
                    summary.get(
                        "valuation_upside"
                    )
                ),
                "investment_score": (
                    summary.get(
                        "fundamental_score"
                    )
                ),
                "valuation_classification": (
                    summary.get(
                        "valuation_classification"
                    )
                ),
                "investment_view": (
                    summary.get(
                        "investment_view"
                    )
                ),
            }
        ]
    )


def save_investment_summary(
    summary: dict,
    output_dir: Path,
) -> Path:
    """
    Save the investment assessment as CSV.
    """
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    dataframe = pd.DataFrame(
        [summary]
    )

    path = (
        output_dir
        / "investment_summary.csv"
    )

    dataframe.to_csv(
        path,
        index=False,
    )

    return path


def save_research_outputs(
    result,
    output_dir: Path,
) -> dict[str, Path]:
    """
    Save the principal outputs generated by
    the integrated research engine.
    """
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    paths: dict[str, Path] = {}

    snapshot = build_research_snapshot(
        result
    )

    paths["research_snapshot"] = (
        save_dataframe(
            snapshot,
            "research_snapshot.csv",
            output_dir,
        )
    )

    paths["investment_summary"] = (
        save_investment_summary(
            result.investment_summary,
            output_dir,
        )
    )

    paths["valuation_summary"] = (
        save_dataframe(
            result.valuation_summary,
            "valuation_summary.csv",
            output_dir,
        )
    )

    paths["scenario_valuations"] = (
        save_dataframe(
            result.scenario_valuations,
            "scenario_valuations.csv",
            output_dir,
        )
    )

    paths["peer_multiples"] = (
        save_dataframe(
            result.peer_multiples,
            "peer_multiples.csv",
            output_dir,
        )
    )

    paths["peer_comparison"] = (
        save_dataframe(
            result.peer_comparison,
            "peer_comparison.csv",
            output_dir,
        )
    )

    paths["peer_valuation"] = (
        save_dataframe(
            result.peer_valuation,
            "peer_valuation.csv",
            output_dir,
        )
    )

    return paths
